create table
  public.accounts (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone not null default now(),
    username text not null,
    password text not null,
    constraint accounts_pkey primary key (id),
    constraint accounts_username_key unique (username)
  ) tablespace pg_default;

create table
  public.answers (
    id bigint generated by default as identity,
    account_id uuid not null,
    answered_at timestamp with time zone not null default now(),
    quiz_id bigint not null,
    answers json not null default '{}'::json,
    scores_earned double precision not null,
    constraint answers_pkey primary key (id),
    constraint answers_account_id_fkey foreign key (account_id) references accounts (id) on update cascade on delete cascade,
    constraint answers_quiz_id_fkey foreign key (quiz_id) references quizzes (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.questions (
    id bigint generated by default as identity,
    quiz_id bigint not null,
    created_at timestamp with time zone not null default now(),
    question text not null,
    type bigint not null,
    options jsonb not null,
    answer text not null,
    index bigint not null,
    constraint questions_pkey primary key (id),
    constraint questions_quiz_id_fkey foreign key (quiz_id) references quizzes (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.quizzes (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    user_id text not null,
    code text not null,
    times_answered bigint not null default '0'::bigint,
    max_points bigint not null default '0'::bigint,
    color bigint not null,
    description text null,
    constraint quizzes_pkey primary key (id),
    constraint quizzes_code_key unique (code)
  ) tablespace pg_default;

create table
  public.tokens (
    token text not null,
    created_at timestamp with time zone not null default now(),
    account_id uuid not null,
    constraint tokens_pkey primary key (token),
    constraint tokens_account_id_fkey foreign key (account_id) references accounts (id) on update cascade on delete cascade
  ) tablespace pg_default;